# Generated by Django 6.0.3 on 2026-04-01 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, max_length=50)),
                ('agent_name', models.CharField(max_length=200)),
                ('customer_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('portfolio_id', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('supervisor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('agency_id', models.CharField(blank=True, max_length=50, null=True)),
                ('recording_url', models.URLField(max_length=2000)),
                ('recording_datetime', models.DateTimeField(db_index=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('product_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('provider_resource_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'call_recordings',
            },
        ),
        migrations.CreateModel(
            name='CallTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_text', models.TextField()),
                ('detected_language', models.CharField(blank=True, max_length=10, null=True)),
                ('total_call_duration', models.IntegerField(blank=True, null=True)),
                ('total_non_speech_duration', models.IntegerField(blank=True, null=True)),
                ('customer_talk_duration', models.IntegerField(blank=True, null=True)),
                ('agent_talk_duration', models.IntegerField(blank=True, null=True)),
                ('customer_sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('agent_sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('next_actionable', models.TextField(blank=True, null=True)),
                ('raw_provider_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='baysys_call_audit.callrecording')),
            ],
            options={
                'db_table': 'call_transcripts',
            },
        ),
        migrations.CreateModel(
            name='ComplianceFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('abusive_language', 'Abusive Language'), ('outside_hours', 'Outside Permitted Hours'), ('restricted_keyword', 'Restricted Keyword'), ('rbi_coc_violation', 'RBI COC Violation'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('description', models.TextField()),
                ('evidence', models.TextField(blank=True, null=True)),
                ('auto_detected', models.BooleanField(default=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_by', models.CharField(blank=True, max_length=50, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_flags', to='baysys_call_audit.callrecording')),
            ],
            options={
                'db_table': 'compliance_flags',
            },
        ),
        migrations.CreateModel(
            name='OwnLLMScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_template_name', models.CharField(max_length=100)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('max_score', models.IntegerField(blank=True, null=True)),
                ('score_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('score_breakdown', models.JSONField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_scores', to='baysys_call_audit.callrecording')),
            ],
            options={
                'db_table': 'own_llm_scores',
            },
        ),
        migrations.CreateModel(
            name='ProviderScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.CharField(max_length=50)),
                ('template_name', models.CharField(blank=True, max_length=200, null=True)),
                ('audit_compliance_score', models.IntegerField(blank=True, null=True)),
                ('max_compliance_score', models.IntegerField(blank=True, null=True)),
                ('score_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('category_data', models.JSONField(blank=True, null=True)),
                ('detected_restricted_keyword', models.BooleanField(default=False)),
                ('restricted_keywords', models.JSONField(default=list)),
                ('raw_score_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_scores', to='baysys_call_audit.callrecording')),
            ],
            options={
                'db_table': 'provider_scores',
            },
        ),
    ]
