# Generated by Django 6.0.3 on 2026-04-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baysys_call_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='fatal_level',
            field=models.IntegerField(default=0, help_text='Computed severity 0-5 from provider boolean scores. 0 = not yet scored.'),
        ),
    ]
