# Generated by Django 6.0.3 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baysys_call_audit', '0002_callrecording_fatal_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='callrecording',
            name='submission_tier',
            field=models.CharField(
                choices=[
                    ('immediate', 'Immediate'),
                    ('normal', 'Normal'),
                    ('off_peak', 'Off Peak'),
                ],
                default='normal',
                db_index=True,
                help_text='Submission priority tier: immediate > normal > off_peak',
                max_length=20,
            ),
        ),
    ]
