# Generated by Django 6.0.3 on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baysys_call_audit', '0003_callrecording_submission_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecording',
            name='recording_url',
            field=models.CharField(max_length=2000),
        ),
    ]
